name: voxmod_voice_studio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Saya set ke 3.0.0 agar lebih aman kompatibilitasnya

dependencies:
  flutter:
    sdk: flutter

  # --- ICONS ---
  cupertino_icons: ^1.0.8

  # --- AUDIO & STORAGE (NEW) ---
  flutter_sound: ^9.2.13  # Perekam & Pemutar Audio Pro
  permission_handler: ^11.3.0 # Manajemen Izin (Mic)
  path_provider: ^2.1.2   # Akses folder penyimpanan HP
  logger: ^2.0.0          # Biar debugging enak dilihat di console

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true