name: voxmod_voice_studio
description: "A AI Voice Converter Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Icons ---
  cupertino_icons: ^1.0.8

  # --- Networking (API) ---
  dio: ^5.4.0

  # --- Audio Logic ---
  flutter_sound: ^9.2.13  # Recorder & Player

  # --- System & Storage ---
  permission_handler: ^11.3.0 # Izin Microphone
  path_provider: ^2.1.2       # Akses Temp Directory

  # --- Utilities ---
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
